"""Componentes públicos do Daniel Job Agent."""

from .enrichment import enrich_job, enrich_opportunities, extract_years_experience
from .models import (
    ApplicationStatus,
    ApplicationTracking,
    CandidateProfile,
    JobOpportunity,
)
from .ingestion import (
    BaseJobAdapter,
    BatchIngestionResult,
    GenericJobAdapter,
    GreenhouseJobAdapter,
    IngestionError,
    IngestionErrorType,
    IngestionResult,
    IngestionWarning,
    LeverJobAdapter,
    MockGreenhouseAdapter,
    MockLeverAdapter,
    combine_ingestion_batches,
    ingest_batch,
)
from .pipeline import (
    DuplicateRecord,
    PipelineResult,
    ProcessedOpportunity,
    process_opportunities,
)
from .profiles import create_daniel_profile
from .rules import (
    GeographicEligibility,
    MatchEvaluation,
    RetentionDecision,
    RolePriority,
    ScoreWeights,
    are_probably_duplicates,
    calculate_match_score,
    classify_role,
    decide_retention,
    evaluate_match,
    evaluate_geographic_eligibility,
    is_clearly_irrelevant_role,
    normalize_company,
    normalize_job_url,
    normalize_location,
    normalize_role,
)
from .sources import (
    GreenhouseJobSource,
    JobSource,
    LeverJobSource,
    SourceResult,
    SourceStatus,
    build_greenhouse_jobs_url,
    build_lever_postings_url,
)

__all__ = [
    "ApplicationStatus",
    "ApplicationTracking",
    "BaseJobAdapter",
    "BatchIngestionResult",
    "CandidateProfile",
    "DuplicateRecord",
    "GeographicEligibility",
    "GenericJobAdapter",
    "GreenhouseJobAdapter",
    "GreenhouseJobSource",
    "IngestionError",
    "IngestionErrorType",
    "IngestionResult",
    "IngestionWarning",
    "JobOpportunity",
    "JobSource",
    "LeverJobAdapter",
    "LeverJobSource",
    "MatchEvaluation",
    "MockGreenhouseAdapter",
    "MockLeverAdapter",
    "PipelineResult",
    "ProcessedOpportunity",
    "RetentionDecision",
    "RolePriority",
    "ScoreWeights",
    "SourceResult",
    "SourceStatus",
    "are_probably_duplicates",
    "calculate_match_score",
    "build_greenhouse_jobs_url",
    "build_lever_postings_url",
    "classify_role",
    "combine_ingestion_batches",
    "create_daniel_profile",
    "decide_retention",
    "enrich_job",
    "enrich_opportunities",
    "evaluate_match",
    "evaluate_geographic_eligibility",
    "extract_years_experience",
    "is_clearly_irrelevant_role",
    "normalize_company",
    "normalize_job_url",
    "normalize_location",
    "normalize_role",
    "ingest_batch",
    "process_opportunities",
]
