"""Componentes públicos do Daniel Job Agent."""

from .models import (
    ApplicationStatus,
    ApplicationTracking,
    CandidateProfile,
    JobOpportunity,
)
from .ingestion import (
    BaseJobAdapter,
    BatchIngestionResult,
    GenericJobAdapter,
    IngestionError,
    IngestionErrorType,
    IngestionResult,
    IngestionWarning,
    MockGreenhouseAdapter,
    MockLeverAdapter,
    combine_ingestion_batches,
    ingest_batch,
)
from .pipeline import (
    DuplicateRecord,
    PipelineResult,
    ProcessedOpportunity,
    process_opportunities,
)
from .profiles import create_daniel_profile
from .rules import (
    GeographicEligibility,
    MatchEvaluation,
    RetentionDecision,
    RolePriority,
    ScoreWeights,
    are_probably_duplicates,
    calculate_match_score,
    classify_role,
    decide_retention,
    evaluate_match,
    evaluate_geographic_eligibility,
    normalize_company,
    normalize_job_url,
    normalize_location,
    normalize_role,
)

__all__ = [
    "ApplicationStatus",
    "ApplicationTracking",
    "BaseJobAdapter",
    "BatchIngestionResult",
    "CandidateProfile",
    "DuplicateRecord",
    "GeographicEligibility",
    "GenericJobAdapter",
    "IngestionError",
    "IngestionErrorType",
    "IngestionResult",
    "IngestionWarning",
    "JobOpportunity",
    "MatchEvaluation",
    "MockGreenhouseAdapter",
    "MockLeverAdapter",
    "PipelineResult",
    "ProcessedOpportunity",
    "RetentionDecision",
    "RolePriority",
    "ScoreWeights",
    "are_probably_duplicates",
    "calculate_match_score",
    "classify_role",
    "combine_ingestion_batches",
    "create_daniel_profile",
    "decide_retention",
    "evaluate_match",
    "evaluate_geographic_eligibility",
    "normalize_company",
    "normalize_job_url",
    "normalize_location",
    "normalize_role",
    "ingest_batch",
    "process_opportunities",
]
