"""Oportunidades fictícias para demonstrar o pipeline sem fontes externas."""

from .models import JobOpportunity


def create_ingestion_demo_records() -> dict[str, list[dict[str, object]]]:
    """Cria registros brutos fictícios em três formatos incompatíveis entre si."""

    return {
        "generic": [
            {
                "company": "  Aurora Metrics  ",
                "title": " Account  Executive ",
                "url": "https://raw.invalid/aurora/ae",
                "location": " Remote - LATAM ",
                "remote": "true",
                "brazil_eligible": "true",
                "description": "Local fictional record",
                "base_salary": "75000",
                "salary_currency": "USD",
                "tools_mentioned": ["Salesforce", "Gong"],
                "industries_mentioned": ["B2B SaaS"],
                "years_experience_required": "5",
            },
            {
                "company": "Northstar Systems",
                "title": "Account Executive",
                "url": "https://raw.invalid/northstar/ae",
                "location": "Remote - US only",
                "remote": True,
                "brazil_eligible": False,
                "base_salary": 90000,
            },
            {
                "company": "Code Meadow",
                "title": "Software Engineer",
                "url": "https://raw.invalid/code/engineer",
                "location": "Remote - LATAM",
                "remote": True,
                "brazil_eligible": True,
            },
            {
                "company": "Missing Title Labs",
                "title": "   ",
                "url": "https://raw.invalid/missing/title",
                "location": "Remote - LATAM",
            },
        ],
        "greenhouse": [
            {
                "organization_name": "Aurora Metrics",
                "position_name": "Account Executive",
                "absolute_url": "https://other.invalid/aurora/account-executive",
                "workplace": "Remote - LATAM",
                "remote": True,
                "brazil_eligible": True,
                "salary": "76000",
                "tools": ["Salesforce"],
            },
            {
                "organization_name": "Orbit Leads",
                "position_name": "SDR",
                "absolute_url": "https://raw.invalid/orbit/sdr",
                "workplace": "Worldwide Remote",
                "remote": "true",
                "brazil_eligible": "true",
            },
            {
                "organization_name": "Vita Path",
                "position_name": "Sales Executive",
                "absolute_url": "https://raw.invalid/vita/sales",
                "workplace": "Remote - Brazil",
                "remote": True,
                "brazil_eligible": True,
                "industries": ["Healthtech"],
            },
            {
                "organization_name": "Broken Salary Co",
                "position_name": "Inside Sales",
                "absolute_url": "https://raw.invalid/broken/salary",
                "workplace": "Remote - LATAM",
                "remote": True,
                "salary": "USD 80k",
            },
        ],
        "lever": [
            {
                "employer": "Cedar Growth",
                "job_title": "Business Development Representative",
                "apply_url": "https://raw.invalid/cedar/bdr",
                "region": "Latin America",
                "remote": "true",
                "brazil_eligible": "true",
                "commitment": "Contractor",
                "stack": ["Apollo", "SalesLoft"],
                "minimum_years": "3",
            },
            {
                "employer": "Open Trail",
                "job_title": "Sales Executive",
                "apply_url": "https://raw.invalid/open/sales",
                "region": "Location not disclosed",
                "remote": True,
                "brazil_eligible": False,
                "compensation": "68000",
                "currency": "USD",
            },
            {
                "employer": "Bridge Commerce",
                "job_title": "Commercial Account Manager",
                "apply_url": "https://raw.invalid/bridge/account-manager",
                "region": "Remote - LATAM",
                "remote": True,
                "brazil_eligible": True,
                "stack": ["HubSpot"],
            },
            {
                "job_title": "Account Executive",
                "apply_url": "https://raw.invalid/missing/company",
                "region": "Remote - LATAM",
            },
        ],
    }


def create_demo_jobs() -> list[JobOpportunity]:
    """Cria 13 vagas fictícias, incluindo uma duplicata intencional."""

    common = {"source": "Fictional local dataset", "remote": True}
    return [
        JobOpportunity(
            company="Aurora Metrics",
            role="Account Executive",
            job_url="https://demo.invalid/aurora/ae",
            location="Remote - LATAM",
            brazil_eligible=True,
            years_experience_required=5,
            tools_mentioned=["Salesforce", "Gong"],
            industries_mentioned=["B2B SaaS"],
            **common,
        ),
        JobOpportunity(
            company="Summit Cloud",
            role="Enterprise Account Executive",
            job_url="https://demo.invalid/summit/enterprise-ae",
            location="Remote - LATAM",
            brazil_eligible=True,
            years_experience_required=7,
            tools_mentioned=["Salesforce"],
            industries_mentioned=["Technology"],
            **common,
        ),
        JobOpportunity(
            company="Canopy Revenue",
            role="Account Executive",
            job_url="https://demo.invalid/canopy/ae",
            location="Remote - Brazil",
            brazil_eligible=True,
            years_experience_required=3,
            tools_mentioned=["HubSpot"],
            **common,
        ),
        JobOpportunity(
            company="Northstar Systems",
            role="Account Executive",
            job_url="https://demo.invalid/northstar/ae",
            location="Remote - US only",
            brazil_eligible=False,
            years_experience_required=5,
            **common,
        ),
        JobOpportunity(
            company="Orbit Leads",
            role="SDR",
            job_url="https://demo.invalid/orbit/sdr",
            location="Worldwide Remote",
            brazil_eligible=True,
            years_experience_required=2,
            tools_mentioned=["SalesLoft", "Apollo"],
            **common,
        ),
        JobOpportunity(
            company="Cedar Growth",
            role="Business Development Representative",
            job_url="https://demo.invalid/cedar/bdr",
            location="Remote - LATAM",
            brazil_eligible=True,
            years_experience_required=3,
            **common,
        ),
        JobOpportunity(
            company="Bridge Commerce",
            role="Commercial Account Manager",
            job_url="https://demo.invalid/bridge/account-manager",
            location="Remote - LATAM",
            brazil_eligible=True,
            responsibilities=["Grow and renew a portfolio of B2B customers"],
            tools_mentioned=["Salesforce"],
            **common,
        ),
        JobOpportunity(
            company="Quiet Harbor",
            role="Account Manager",
            job_url="https://demo.invalid/quiet/account-manager",
            location="Remote",
            brazil_eligible=False,
            **common,
        ),
        JobOpportunity(
            company="Open Trail",
            role="Sales Executive",
            job_url="https://demo.invalid/open-trail/sales",
            location="Location not disclosed",
            brazil_eligible=False,
            tools_mentioned=["HubSpot"],
            **common,
        ),
        JobOpportunity(
            company="Signal Forge",
            role="Inside Sales",
            job_url="https://demo.invalid/signal/inside-sales",
            location="Latin America",
            brazil_eligible=True,
            tools_mentioned=["Salesforce", "ZoomInfo", "Aircall"],
            **common,
        ),
        JobOpportunity(
            company="Vita Path",
            role="Sales Executive",
            job_url="https://demo.invalid/vita/sales",
            location="Remote - Brazil",
            brazil_eligible=True,
            industries_mentioned=["Healthtech"],
            **common,
        ),
        JobOpportunity(
            company="Code Meadow",
            role="Software Engineer",
            job_url="https://demo.invalid/code/software-engineer",
            location="Remote - LATAM",
            brazil_eligible=True,
            industries_mentioned=["Technology"],
            **common,
        ),
        JobOpportunity(
            company="  Aurora Metrics  ",
            role="Account  Executive",
            job_url="https://demo.invalid/aurora/ae?source=duplicate",
            location="Remote - LATAM",
            brazil_eligible=True,
            **common,
        ),
    ]
