"""Oportunidades fictícias para demonstrar o pipeline sem fontes externas."""

from .models import JobOpportunity


def create_demo_jobs() -> list[JobOpportunity]:
    """Cria 13 vagas fictícias, incluindo uma duplicata intencional."""

    common = {"source": "Fictional local dataset", "remote": True}
    return [
        JobOpportunity(
            company="Aurora Metrics",
            role="Account Executive",
            job_url="https://demo.invalid/aurora/ae",
            location="Remote - LATAM",
            brazil_eligible=True,
            years_experience_required=5,
            tools_mentioned=["Salesforce", "Gong"],
            industries_mentioned=["B2B SaaS"],
            **common,
        ),
        JobOpportunity(
            company="Summit Cloud",
            role="Enterprise Account Executive",
            job_url="https://demo.invalid/summit/enterprise-ae",
            location="Remote - LATAM",
            brazil_eligible=True,
            years_experience_required=7,
            tools_mentioned=["Salesforce"],
            industries_mentioned=["Technology"],
            **common,
        ),
        JobOpportunity(
            company="Canopy Revenue",
            role="Account Executive",
            job_url="https://demo.invalid/canopy/ae",
            location="Remote - Brazil",
            brazil_eligible=True,
            years_experience_required=3,
            tools_mentioned=["HubSpot"],
            **common,
        ),
        JobOpportunity(
            company="Northstar Systems",
            role="Account Executive",
            job_url="https://demo.invalid/northstar/ae",
            location="Remote - US only",
            brazil_eligible=False,
            years_experience_required=5,
            **common,
        ),
        JobOpportunity(
            company="Orbit Leads",
            role="SDR",
            job_url="https://demo.invalid/orbit/sdr",
            location="Worldwide Remote",
            brazil_eligible=True,
            years_experience_required=2,
            tools_mentioned=["SalesLoft", "Apollo"],
            **common,
        ),
        JobOpportunity(
            company="Cedar Growth",
            role="Business Development Representative",
            job_url="https://demo.invalid/cedar/bdr",
            location="Remote - LATAM",
            brazil_eligible=True,
            years_experience_required=3,
            **common,
        ),
        JobOpportunity(
            company="Bridge Commerce",
            role="Commercial Account Manager",
            job_url="https://demo.invalid/bridge/account-manager",
            location="Remote - LATAM",
            brazil_eligible=True,
            responsibilities=["Grow and renew a portfolio of B2B customers"],
            tools_mentioned=["Salesforce"],
            **common,
        ),
        JobOpportunity(
            company="Quiet Harbor",
            role="Account Manager",
            job_url="https://demo.invalid/quiet/account-manager",
            location="Remote",
            brazil_eligible=False,
            **common,
        ),
        JobOpportunity(
            company="Open Trail",
            role="Sales Executive",
            job_url="https://demo.invalid/open-trail/sales",
            location="Location not disclosed",
            brazil_eligible=False,
            tools_mentioned=["HubSpot"],
            **common,
        ),
        JobOpportunity(
            company="Signal Forge",
            role="Inside Sales",
            job_url="https://demo.invalid/signal/inside-sales",
            location="Latin America",
            brazil_eligible=True,
            tools_mentioned=["Salesforce", "ZoomInfo", "Aircall"],
            **common,
        ),
        JobOpportunity(
            company="Vita Path",
            role="Sales Executive",
            job_url="https://demo.invalid/vita/sales",
            location="Remote - Brazil",
            brazil_eligible=True,
            industries_mentioned=["Healthtech"],
            **common,
        ),
        JobOpportunity(
            company="Code Meadow",
            role="Software Engineer",
            job_url="https://demo.invalid/code/software-engineer",
            location="Remote - LATAM",
            brazil_eligible=True,
            industries_mentioned=["Technology"],
            **common,
        ),
        JobOpportunity(
            company="  Aurora Metrics  ",
            role="Account  Executive",
            job_url="https://demo.invalid/aurora/ae?source=duplicate",
            location="Remote - LATAM",
            brazil_eligible=True,
            **common,
        ),
    ]
